language: node_js
node_js:
  - 'node'

jobs:
  include:
    - stage: setup
      script: yarn && yarn start
      script: yarn wait-on http://localhost:8000
    - stage: test
      script: yarn cypress run
    - stage: build
      script: yarn build
    - stage: deploy
      deploy:
        provider: pages
        target_branch: master
        local_dir: public
        skip_cleanup: true
        github_token: $DEPLOY_TOKEN
        keep_history: true
        on:
          branch: dev
